# Development Configuration for Notification Service
server:
  port: 8084

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:mysql://localhost:3306/school_fee_register?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: schooluser
    password: schoolpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

# WhatsApp Business API Configuration (Test/Development)
whatsapp:
  api:
    url: ${WHATSAPP_API_URL:https://graph.facebook.com/v17.0}
  phone:
    number:
      id: ${WHATSAPP_PHONE_NUMBER_ID:test_phone_number_id}
  access:
    token: ${WHATSAPP_ACCESS_TOKEN:test_access_token}

# Enhanced logging for debugging
logging:
  level:
    com.school.notificationservice: DEBUG
    com.school.notificationservice.service.WhatsAppService: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Eureka configuration for development
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always 